version: '3'

services:
  myweb:
    build:
      context: ./app
      lables:
        AppName: "OffersApp"
        Description: "Offers for the Products"
    container_name: mywebsite
    environment:
      Name: Goutham
      APP_HOME: /app
    image: myweb:latest
    ports:
      - "5000:5000"
    restart: on-failure

  redis:
    image: "redis:latest"
    restart: no-failure
    depends_on:
      - "myweb"
